### ISSUE TITLE
More then one existing secret in the Helm chart options 

### ISSUE THREAD

**Issue by dimashenkov** [kafbat/helm-charts#10]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md) and the feature is not present there

### Describe the feature you're interested in

For example I need to pass different secrets for SSO and for the Kafka cluster .
Would be good to to change deployment.yaml in the Helm chart to be able to pass more then one existing secret in values.yaml, like this . 
```
            {{- if .Values.existingSecrets }}
              {{- range .Values.existingSecrets }}
              - secretRef:
                  name: {{ . }}
              {{- end }}
            {{- end }}
```

### Version you're running

27c5e61

**Comment by dimashenkov** [comment]
> Could you please consider to use other tools to construct cumulative secret. The tools which can help with this: ClusterSecret, ExternalSecrets. Also please check kustomize secret generator, maybe it will suit your needs.

I have crated secrets with SeledSecret but I need to pass them to the values.yaml, Im not sure I understand your suggestion

**Comment by dimashenkov** [comment]
to construct cumulative secrets is not that convenient but fine.

**Comment by Haarolean** [comment]
The problem with this approach is that changes like this will be breaking for the users who already use one secret as far as I understand it. However, we could accept PRs with the changes which are non-breaking. Feel free to raise one if you find it viable.
