### ISSUE TITLE
Helm chart not working with ARM node

### ISSUE THREAD

**Issue by ognjenVlad** [kafbat/helm-charts#15]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://ui.docs.kafbat.io/faq/common-problems)
- [X] I've searched for an already existing issues [here (legacy)](https://github.com/kafbat/kafka-ui/issues) and [here](https://github.com/kafbat/helm-charts/issues)
- [X] I've tried installing latest charts and the issue still persists there
- [X] I'm running a supported version of the application & chart which is listed [here](https://github.com/kafbat/kafka-ui/blob/master/.github/SECURITY.md)

### Describe the bug (actual behavior)

After deploying Helm chart version 1.4.0 to ARM nodes, pod is failing with error `exec format error `, I can see that some similar behaviour is reported [here](https://github.com/kafbat/kafka-ui/issues/254#issuecomment-2034699633). 
After inspecting the image `docker image inspect ghcr.io/kafbat/kafka-ui:v1.0.0 --format '{{ .Os }}/{{ .Architecture }}'`, it shows `linux/arm64` locally but looks like image is not properly built.

### Expected behavior

Pod to start without exec format errors

### Your installation details

1. v1.0.0
2. 1.4.0
3. 
`kafka:
    clusters:
      - name: test
        bootstrapServers: ${brokers}
  auth:
    type: disabled
  management:
    health:
      ldap:
        enabled: false`

### Steps to reproduce

- Deploy kafbat Helm chart to ARM node

**Comment by Haarolean** [comment]
Hey, please upvote #376, we'll track the progress there
