### ISSUE TITLE
add deployment custom labels

### ISSUE THREAD

**Issue by crimarz** [kafbat/helm-charts#18]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://ui.docs.kafbat.io/faq/common-problems)
- [X] I've searched for an already existing issues [here (legacy)](https://github.com/kafbat/kafka-ui/issues) and [here](https://github.com/kafbat/helm-charts/issues)
- [X] I've tried installing latest charts and the issue still persists there
- [X] I'm running a supported version of the application & chart which is listed [here](https://github.com/kafbat/kafka-ui/blob/master/.github/SECURITY.md)

### Describe the bug (actual behavior)

I think it will be useful to permit custom labels for deployment as already in place for pods (.Values.podLabels)

### Expected behavior

possibility to set a new value (.Values.deploymentLabels ? ) with a list of custom labels for deployment 

### Your installation details

Appversion:v1.0.0
Chartversion:kafka-ui-1.4.0

### Steps to reproduce

n/a

**Comment by Haarolean** [comment]
Hi, feel free to raise a PR for this :)
